# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps: 
- script: | 
    git  push -f "https://$DEPLOYMENT_USRE:$DEPLOYMENT_PASS@DEPLOYMENT_URL" HEAD:master
  env:
    DEPLOYMENT_URL: $(DEPLOYMENT_URL)
    DEPLOYMENT_USER: $(DEPLOYMENT_USER)
    DEPLOYMENT_PASS: $(DEPLOYMENT_PASS)
  displayName: 'LocalGit Deploy'


