# Generated by Django 3.2.4 on 2021-07-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationApp', '0002_rename_user_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='opinion',
            field=models.TextField(default='Add opinion', max_length=1000),
        ),
    ]
