# Generated by Django 3.2.4 on 2021-07-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationApp', '0003_auto_20210705_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='opinion',
            field=models.TextField(max_length=1000),
        ),
    ]
